import { Link } from "react-router-dom";
import {
  AlertTriangle,
  Bot,
  Briefcase,
  FileText,
  Sparkles,
  UserCheck,
} from "lucide-react";
import { AgentStatusDot, statusLabel } from "@/components/AgentStatus";
import { EmptyState, Skeleton } from "@/components/EmptyState";
import { PageHeader } from "@/components/PageHeader";
import { StatusBadge } from "@/components/StatusBadge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useAgent } from "@/hooks/useAgent";
import { useApplications } from "@/hooks/useApplications";
import { useDashboard } from "@/hooks/useDashboard";
import { useAuthStore } from "@/stores/authStore";

export function DashboardPage() {
  const user = useAuthStore((state) => state.user);
  const { data, isLoading, isError } = useDashboard();
  const { data: agent } = useAgent();
  const { data: applications } = useApplications();
  const recent = applications?.items.slice(0, 5) ?? [];
  const running = (data?.agentStatus ?? agent?.agentStatus) === "RUNNING";

  const cards = [
    {
      label: "Agent",
      value: data ? statusLabel(data.agentStatus) : "—",
      to: "/agent",
      hint: running ? "Looking and applying" : "Start it to apply for you",
      icon: Bot,
      numeric: false,
    },
    {
      label: "Jobs scanned",
      value: data?.jobsScanned ?? "—",
      to: "/jobs",
      hint: "From public boards",
      icon: Briefcase,
      numeric: true,
    },
    {
      label: "Matches",
      value: data?.matching ?? "—",
      to: "/matches",
      hint: "Scored from your CV",
      icon: Sparkles,
      numeric: true,
    },
    {
      label: "Applications",
      value: data?.applications ?? "—",
      to: "/applications",
      hint: "Every attempt kept",
      icon: FileText,
      numeric: true,
    },
    {
      label: "Needs you",
      value: data?.manualReview ?? "—",
      to: "/applications?status=MANUAL_REVIEW",
      hint: "Finish on the company site",
      icon: UserCheck,
      numeric: true,
    },
    {
      label: "Rejected",
      value: data?.rejected ?? "—",
      to: "/analytics",
      hint: "Closed loops",
      icon: AlertTriangle,
      numeric: true,
    },
  ] as const;

  return (
    <div className="mx-auto max-w-6xl space-y-8">
      <PageHeader
        eyebrow="Overview"
        title={`Welcome${user ? `, ${user.firstName}` : ""}`}
        description="Counts from your verified profile, matches, and applications — not generated by the model."
        action={
          <Button asChild>
            <Link to={running ? "/applications" : "/agent"}>{running ? "View applications" : "Start the agent"}</Link>
          </Button>
        }
      />

      {running ? (
        <div className="flex items-start gap-3 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">
          <AgentStatusDot status="RUNNING" className="mt-1.5" />
          <div>
            <p className="font-medium">Agent is looking and applying</p>
            <p className="mt-0.5 text-emerald-800/80">
              It applies within your cap, then leaves a copy of each attempt on Applications.
            </p>
          </div>
        </div>
      ) : (
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0">
            <div>
              <CardTitle className="text-base">Let the agent apply for you</CardTitle>
              <CardDescription>
                It turns auto-apply on, scans jobs that match your CV, and applies within your daily cap.
              </CardDescription>
            </div>
            <Button asChild>
              <Link to="/agent">Start looking</Link>
            </Button>
          </CardHeader>
        </Card>
      )}

      {isError && <p className="text-sm text-destructive">Could not load dashboard.</p>}

      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-3">
        {isLoading
          ? Array.from({ length: 6 }).map((_, index) => (
              <Card key={index}>
                <CardContent className="space-y-3 pt-6">
                  <Skeleton className="h-4 w-24" />
                  <Skeleton className="h-8 w-16" />
                </CardContent>
              </Card>
            ))
          : cards.map((card) => {
              const Icon = card.icon;
              return (
                <Link key={card.label} to={card.to}>
                  <Card className="h-full transition-colors hover:border-primary/30 hover:bg-muted/30">
                    <CardHeader className="flex flex-row items-start justify-between space-y-0 pb-2">
                      <CardDescription>{card.label}</CardDescription>
                      <span className="grid size-8 place-items-center rounded-lg bg-muted text-muted-foreground">
                        <Icon className="size-4" />
                      </span>
                    </CardHeader>
                    <CardContent>
                      <p className={card.numeric ? "stat-value" : "text-3xl font-semibold tracking-tight"}>
                        {card.value}
                      </p>
                      <p className="mt-2 text-xs text-muted-foreground">{card.hint}</p>
                    </CardContent>
                  </Card>
                </Link>
              );
            })}
      </div>

      <Card>
        <CardHeader className="flex flex-row items-center justify-between space-y-0">
          <div>
            <CardTitle className="text-base">Recent applications</CardTitle>
            <CardDescription>Latest attempts, including ones that still need you.</CardDescription>
          </div>
          <Link to="/applications" className="text-sm font-medium text-primary hover:underline">
            See all
          </Link>
        </CardHeader>
        <CardContent className="px-0 pb-2">
          {recent.length === 0 ? (
            <EmptyState
              className="mx-6 mb-4"
              title="No applications yet"
              description="Start the agent or apply from For you and Find jobs."
            />
          ) : (
            <ul className="divide-y">
              {recent.map((application) => (
                <li key={application.id}>
                  <Link
                    to={`/applications/${application.id}`}
                    className="surface-row flex items-center justify-between gap-3 px-6 py-3"
                  >
                    <div className="min-w-0">
                      <p className="truncate text-sm font-medium">{application.job.title}</p>
                      <p className="truncate text-xs text-muted-foreground">{application.job.company}</p>
                    </div>
                    <div className="flex shrink-0 items-center gap-3">
                      <span className="hidden text-xs tabular-nums text-muted-foreground sm:inline">
                        {application.matchScore}
                      </span>
                      <StatusBadge status={application.status} />
                    </div>
                  </Link>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
