import { Link } from "react-router-dom";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { PageHeader } from "@/components/PageHeader";
import { useAuthStore } from "@/stores/authStore";
import { useDashboard } from "@/hooks/useDashboard";

export function DashboardPage() {
  const user = useAuthStore((state) => state.user);
  const { data, isLoading, isError } = useDashboard();

  const cards = [
    { label: "Active agent", value: data ? data.agentStatus : "—", to: "/agent", hint: "Runtime only" },
    { label: "Jobs scanned", value: data?.jobsScanned ?? "—", to: "/jobs", hint: "From discovery" },
    { label: "Matches", value: data?.matching ?? "—", to: "/matches", hint: "Scored from your CV" },
    { label: "Applications", value: data?.applications ?? "—", to: "/applications", hint: "Every attempt" },
    { label: "Manual review", value: data?.manualReview ?? "—", to: "/applications?status=MANUAL_REVIEW", hint: "Needs you" },
    { label: "Rejected", value: data?.rejected ?? "—", to: "/analytics", hint: "Closed loops" },
  ] as const;

  return (
    <div className="mx-auto max-w-6xl space-y-10">
      <PageHeader
        title={`Welcome${user ? `, ${user.firstName}` : ""}`}
        description="Counts from your verified profile, matches, and applications. These numbers are not generated by the model."
      />

      {isLoading && <p className="text-sm text-muted-foreground">Loading dashboard...</p>}
      {isError && <p className="text-sm text-destructive">Could not load dashboard.</p>}

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-3">
        {cards.map((card, index) => (
          <Link key={card.label} to={card.to} className={index === 0 ? "sm:col-span-2 xl:col-span-1" : undefined}>
            <Card className="h-full hover:bg-muted/40">
              <CardHeader className="pb-2">
                <CardDescription>{card.label}</CardDescription>
              </CardHeader>
              <CardContent>
                <p className="text-3xl font-semibold tracking-tight">{card.value}</p>
                <p className="mt-2 text-xs text-muted-foreground">{card.hint}</p>
              </CardContent>
            </Card>
          </Link>
        ))}
      </div>

      {data && !data.autoApplyEnabled && (
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Auto-apply is off</CardTitle>
            <CardDescription>
              Start the agent from the Agent page after enabling auto-apply in Preferences. The scheduler will
              not submit anything until both are on.
            </CardDescription>
          </CardHeader>
        </Card>
      )}
    </div>
  );
}
